package cz.smartexpensetracker.smart_expense_tracker.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Data
@Entity
public class Transaction {

    // Primary key of the Transaction entity, autogenerated UUID
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    // Monetary amount of the transaction, uses BigDecimal for precision
    private BigDecimal amount;

    // Description of the transaction, must not be blank
    @NotBlank(message = "You have to enter a description!")
    private String description;

    // Date and time when the transaction occurred, must not be null
    @NotNull(message = "You have to specify the date!")
    private LocalDateTime date;

    // Many-to-one relationship to User, eagerly fetched; prevents cyclic JSON serialization with JsonBackReference
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonBackReference(value = "user-transactions")
    private User user;

    // Many-to-one relationship to Budget, eagerly fetched
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "budget_id", nullable = false)
    private Budget budget;
}