package cz.smartexpensetracker.smart_expense_tracker.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Entity
@Data
public class User {

    // Primary key of the User entity, autogenerated UUID
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    // Username of the user, must not be blank
    @NotBlank(message = "You have to enter an username!")
    private String username;

    // One-to-many relationship with Transaction entity, cascades all operations and removes orphans
    // Managed side of the JSON serialization to avoid cyclic references
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference(value = "user-transactions")
    private List<Transaction> transactions = new ArrayList<>();

    // One-to-many relationship with Budget entity, cascades all operations and removes orphans
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference(value = "user-budgets")
    private List<Budget> budgets = new ArrayList<>();

    // One-to-many relationship with Category entity, cascades all operations and removes orphans
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference(value = "user-categories")
    private List<Category> categories = new ArrayList<>();
}